version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
  kibana:
    image: 'kibana:7.9.2'  
    ports:
      - '5601:5601'  

  logstash:
    image: logstash:7.9.2
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true   
  DB:
    image: "postgres"
    container_name: DB
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=crossynDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  crbackend:
    
    build: ./back-end
    container_name: crbackend

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DB:5432/crossynDB
      - DB_SERVER=crossynDB
      - POSTGRES_DB=crossynDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 8080:8080
    links:
      - DB

  crfrontend:
    build: ./front-end
    container_name: crfrontend
    ports:
      - 3000:3000
    links:
      - crbackend

volumes:
  pg-data: